/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#0d9488",
        "primary-container": "#ccfbf1",
        "on-primary": "#ffffff",
        "on-primary-container": "#134e4a",
        secondary: "#0f766e",
        "secondary-container": "#f0fdfa",
        surface: "#ffffff",
        "surface-variant": "#f1f5f9",
        "surface-container": "#f8fafc",
        "surface-container-low": "#ffffff",
        "surface-container-high": "#f0fdfa",
        background: "#f0fdfa",
        "on-surface": "#134e4a",
        "on-surface-variant": "#64748b",
        "on-background": "#134e4a",
        outline: "#e2e8f0",
        "outline-variant": "#e2e8f0",
        error: "#ef4444",
        "error-container": "#fee2e2",
        success: "#10b981",
        "success-container": "#d1fae5",
        "on-success-container": "#064e3b",
        warning: "#f59e0b",
        "warning-container": "#fef3c7",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-mobile": "20px",
        "stack-sm": "8px",
        base: "8px",
        gutter: "24px",
        "container-padding-desktop": "40px",
        "stack-lg": "32px",
        "stack-md": "16px",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      boxShadow: {
        soft: "0 4px 20px -2px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)",
        card: "0 10px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -2px rgba(0, 0, 0, 0.02)",
      },
    },
  },
  plugins: [],
};